# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utc_sys.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rutc_sys.proto\x12\x03utc\"G\n\x16\x41PPParaHeartbeatReport\x12\x14\n\x0csys_timezone\x18\x14 \x01(\x11\x12\x17\n\x0fsys_timezone_id\x18\x15 \x01(\t\"\x0f\n\rSysUTCRequest\"(\n\x10SysUTCRequestACK\x12\x14\n\x0csys_utc_time\x18\x01 \x01(\r\"\x0f\n\rSysRTCInfoGet\"f\n\x10SysRTCInfoGetACK\x12\x14\n\x0csys_utc_time\x18\x01 \x01(\r\x12\x14\n\x0csys_timezone\x18\x02 \x01(\x11\x12\x11\n\ttime_type\x18\x03 \x01(\r\x12\x13\n\x0btimezone_id\x18\x04 \x01(\t\"\"\n\nSysUTCSync\x12\x14\n\x0csys_utc_time\x18\x01 \x01(\r\"!\n\x0fSetCmdResultAck\x12\x0e\n\x06result\x18\x01 \x01(\x11\"\'\n\x0fSysTimezoneSync\x12\x14\n\x0csys_timezone\x18\x01 \x01(\x11\"(\n\x11SysTimezoneIDSync\x12\x13\n\x0btimezone_id\x18\x01 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utc_sys_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPPARAHEARTBEATREPORT._serialized_start=22
  _APPPARAHEARTBEATREPORT._serialized_end=93
  _SYSUTCREQUEST._serialized_start=95
  _SYSUTCREQUEST._serialized_end=110
  _SYSUTCREQUESTACK._serialized_start=112
  _SYSUTCREQUESTACK._serialized_end=152
  _SYSRTCINFOGET._serialized_start=154
  _SYSRTCINFOGET._serialized_end=169
  _SYSRTCINFOGETACK._serialized_start=171
  _SYSRTCINFOGETACK._serialized_end=273
  _SYSUTCSYNC._serialized_start=275
  _SYSUTCSYNC._serialized_end=309
  _SETCMDRESULTACK._serialized_start=311
  _SETCMDRESULTACK._serialized_end=344
  _SYSTIMEZONESYNC._serialized_start=346
  _SYSTIMEZONESYNC._serialized_end=385
  _SYSTIMEZONEIDSYNC._serialized_start=387
  _SYSTIMEZONEIDSYNC._serialized_end=427
# @@protoc_insertion_point(module_scope)
